package teskop;


import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.swing.JRViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class Anggota1 extends javax.swing.JFrame {

    /**
     * Creates new form Anggota1
     */
    public String nama,alamat,hp,jk,id,kataKunci;
    static int dasarCari;
    public Anggota1() {
        initComponents();
        getData();
    }
    public void getData(){
        DefaultTableModel tabel1= new DefaultTableModel();
        tabel1.addColumn("Nama");
        tabel1.addColumn("Alamat");
        tabel1.addColumn("Jenis Kelamin");
        tabel1.addColumn(" No hp");
        try {
           
           Connection conn = Koneksi.koneksiDB();
           Statement stm = conn.createStatement();
           ResultSet sql = stm.executeQuery("select * from anggota");
           while(sql.next()){
                tabel1.addRow(new Object[]{
                    sql.getString(2),
                    sql.getString(3),
                    sql.getString(4),
                    sql.getString(5),
                });
            }
            tabel.setModel(tabel1);
        }catch (SQLException e) {
        }
    }
     public void getTabel(){
        try {
            int row=tabel.getSelectedRow();
            String tabel_kiri=(tabel.getModel().getValueAt(row, 0).toString());
            String hpp=(tabel.getModel().getValueAt(row, 3).toString());
            java.sql.Connection conn= (java.sql.Connection)Koneksi.koneksiDB();
            java.sql.Statement stm= conn.createStatement();
            java.sql.ResultSet sql= stm.executeQuery("select * from anggota where nama='"+tabel_kiri+"' and hp = '"+hpp+"'" );
            if (sql.next()){
                id = sql.getString("id");
                nama=sql.getString("nama");
                alamat=sql.getString("alamat");
                hp=sql.getString("hp");
                jk=sql.getString("jk");
            }
            
        }catch(Exception e){
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        namatext = new javax.swing.JTextField();
        alamattext = new javax.swing.JTextField();
        kelamintext = new javax.swing.JTextField();
        hptext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sim = new javax.swing.JButton();
        del = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        key = new javax.swing.JTextField();
        cr = new javax.swing.JComboBox();
        cari = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bck = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pdfallanggota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 131, 700, 158));

        namatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel2.setText("Alamat");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel3.setText("Jenis Kelamin");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel4.setText("Telepon");

        sim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/simpan.png"))); // NOI18N
        sim.setContentAreaFilled(false);
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/hps.png"))); // NOI18N
        del.setContentAreaFilled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        ad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/tambah.png"))); // NOI18N
        ad.setContentAreaFilled(false);
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                        .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kelamintext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addComponent(hptext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addComponent(alamattext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addComponent(namatext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namatext, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alamattext, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelamintext, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hptext)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(del)
                    .addComponent(sim)
                    .addComponent(ad)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 930, -1));

        key.setText("Pencarian");
        key.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keyKeyReleased(evt);
            }
        });
        getContentPane().add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 84, 249, 40));

        cr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nama", "Alamat", "No Hp" }));
        cr.setToolTipText("Pilih Kateogri");
        cr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crMouseReleased(evt);
            }
        });
        getContentPane().add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 84, 62, 41));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/cari.png"))); // NOI18N
        cari.setContentAreaFilled(false);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 84, 94, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/clear.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 84, 102, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/text/MANAJEMEN-ANGGOTA(1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/Main Menu.png"))); // NOI18N
        bck.setContentAreaFilled(false);
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 192, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/print.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 192, -1));

        pdfallanggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/Laporan daftar anggota.png"))); // NOI18N
        pdfallanggota.setContentAreaFilled(false);
        pdfallanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfallanggotaActionPerformed(evt);
            }
        });
        getContentPane().add(pdfallanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 192, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed

        Update u = new Update();
        String a1,a2,a3,a4;
        a1 = namatext.getText();
        a2 = alamattext.getText();
        a3 = kelamintext.getText();
        a4 = hptext.getText();
        System.out.println("bej"+a1+"::"+a2+"::"+a3+"::"+a4+"::"+id);
        u.up(a1, a2, a3, a4, id);
        Anggota1 a = new Anggota1();
        a.setVisible(true);
        this.dispose();
            
    }//GEN-LAST:event_simActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        getTabel();
        System.out.println(nama+"::"+alamat+"::"+hp+"::"+jk+"::"+id);
        namatext.setText(nama);
        alamattext.setText(alamat);
        kelamintext.setText(jk);
        hptext.setText(hp);
    }//GEN-LAST:event_tabelMouseClicked

    private void namatextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatextActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        Update u = new Update();
        u.deleteAnggota(id);
         Anggota1 a = new Anggota1();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_delActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckActionPerformed
    String na,ala,ja,ha;
    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
            na = namatext.getText();
            ala = alamattext.getText();
            ja= kelamintext.getText();
            ha = hptext.getText();
        if( "".equals(na) || "".equals(ala) || "".equals(ha)|| "".equals(ja))
        {
            JOptionPane.showMessageDialog(null,"Belum keisi full");
            
        }
        else {
            
            Update u = new Update();
            u.tambahAnggota(na, ala, ja, ha);
            Anggota1 a = new Anggota1();
            a.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_adActionPerformed

private void pdfallanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfallanggotaActionPerformed
        try {
            Date ys=new Date(); // membuat oject ys dari class Date 
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd"); //membuat object
           Map<String, Object> parameters = new HashMap<String, Object>();
           JasperPrint print = JasperFillManager.fillReport("./Laporan/Ang.jasper", parameters, Koneksi.koneksiDB());
           JRExporter exporter = new JRPdfExporter();
           exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
           exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Anggota/Laporan Semua Anggota ("+s.format(ys)+").pdf")); // your output goes here
           exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Anggota1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Anggota1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}//GEN-LAST:event_pdfallanggotaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         File namaFile = new File("./Laporan/Ang.jasper");
        try {           
            JasperReport jasper=(net.sf.jasperreports.engine.JasperReport)
            net.sf.jasperreports.engine.util.JRLoader.loadObject(namaFile.getPath());      
           JasperPrint jp=JasperFillManager.fillReport(jasper, null,Koneksi.koneksiDB());
            net.sf.jasperreports.view.JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
      
}//GEN-LAST:event_jButton1ActionPerformed

private void crMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseClicked
    dasarCari = cr.getSelectedIndex();
    cari.setEnabled(true);
    System.out.print(dasarCari);
}//GEN-LAST:event_crMouseClicked

private void crMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseReleased
    dasarCari = cr.getSelectedIndex();
    cari.setEnabled(true);System.out.print(dasarCari);
}//GEN-LAST:event_crMouseReleased

private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        try {
            kataKunci = key.getText();
            DefaultTableModel tabel1= new DefaultTableModel();
                tabel1.addColumn("Nama");
                tabel1.addColumn("Alamat");
                tabel1.addColumn("Jenis Kelamin");
                tabel1.addColumn("No Hp");           
                   Connection conn = Koneksi.koneksiDB();
                   Statement stm = conn.createStatement();
                   ResultSet sql;
                   if(dasarCari==0){System.out.print("cari nama + "+kataKunci);
                    sql = stm.executeQuery("select * from anggota where nama like '%"+kataKunci+"%';");}
                   else if(dasarCari==1){
                    sql = stm.executeQuery("select * from anggota where alamat like '%"+kataKunci+"%';");}
                   else{
                    sql = stm.executeQuery("select * from anggota where hp like '%"+kataKunci+"%';");    }
                   while(sql.next()){
                        tabel1.addRow(new Object[]{
                            sql.getString(2),
                            sql.getString(3),
                            sql.getString(4),
                            sql.getString(5)
                        });
                    }
                    tabel.setModel(tabel1);
        } catch (SQLException ex) {
            Logger.getLogger(Pengurus.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_cariActionPerformed

private void keyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyKeyReleased
     dasarCari = cr.getSelectedIndex();
}//GEN-LAST:event_keyKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    getData();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggota1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JTextField alamattext;
    private javax.swing.JButton bck;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox cr;
    private javax.swing.JButton del;
    private javax.swing.JTextField hptext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kelamintext;
    private javax.swing.JTextField key;
    private javax.swing.JTextField namatext;
    private javax.swing.JButton pdfallanggota;
    private javax.swing.JButton sim;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
