package teskop;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.swing.JRViewer;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Laporan.java
 *
 * Created on Oct 20, 2016, 9:53:21 PM
 */
/**
 *
 * @author Windows 8.1 Pro
 */
public class Laporan extends javax.swing.JFrame {

    /** Creates new form Laporan */
    public Laporan() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LaporanPenabungan = new javax.swing.JButton();
        LaporanPeminjaman = new javax.swing.JButton();
        PrintLaporanTabungan = new javax.swing.JButton();
        printLaporanPinjam = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lapTabByParamm = new javax.swing.JButton();
        LapPinjam = new javax.swing.JButton();
        prinLapByParam = new javax.swing.JButton();
        prinLapPinjam = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setFont(new java.awt.Font("Dialog", 0, 18));
        t1.setText("yyyy/mm/dd");

        t2.setFont(new java.awt.Font("Dialog", 0, 18));
        t2.setText("yyyy/mm/dd");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel1.setText("S/D");

        LaporanPenabungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/Laporan semua tabungna.png"))); // NOI18N
        LaporanPenabungan.setContentAreaFilled(false);
        LaporanPenabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPenabunganActionPerformed(evt);
            }
        });

        LaporanPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/laporan semua pinjam.png"))); // NOI18N
        LaporanPeminjaman.setContentAreaFilled(false);
        LaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPeminjamanActionPerformed(evt);
            }
        });

        PrintLaporanTabungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/print semua tab.png"))); // NOI18N
        PrintLaporanTabungan.setContentAreaFilled(false);
        PrintLaporanTabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintLaporanTabunganActionPerformed(evt);
            }
        });

        printLaporanPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/print semua pinjam.png"))); // NOI18N
        printLaporanPinjam.setContentAreaFilled(false);
        printLaporanPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLaporanPinjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LaporanPenabungan, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LaporanPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printLaporanPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintLaporanTabungan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LaporanPenabungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LaporanPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintLaporanTabungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printLaporanPinjam))
        );

        lapTabByParamm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/laporan tabung.png"))); // NOI18N
        lapTabByParamm.setContentAreaFilled(false);
        lapTabByParamm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapTabByParammActionPerformed(evt);
            }
        });

        LapPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/lapi pinjam.png"))); // NOI18N
        LapPinjam.setContentAreaFilled(false);
        LapPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapPinjamActionPerformed(evt);
            }
        });

        prinLapByParam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/print lap tabungan.png"))); // NOI18N
        prinLapByParam.setContentAreaFilled(false);
        prinLapByParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prinLapByParamActionPerformed(evt);
            }
        });

        prinLapPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/New folder (2)/print lap pinjaman.png"))); // NOI18N
        prinLapPinjam.setContentAreaFilled(false);
        prinLapPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prinLapPinjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prinLapPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prinLapByParam, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LapPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lapTabByParamm, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lapTabByParamm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LapPinjam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prinLapByParam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prinLapPinjam)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/text/LAPORAN(1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/Main Menu.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/lihat laporan.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void LaporanPenabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPenabunganActionPerformed
        try {
            Date ys=new Date(); // membuat oject ys dari class Date 
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd"); //membuat object
            Map<String, Object> parameters = new HashMap<String, Object>();
            JasperPrint print = JasperFillManager.fillReport("./Laporan/semuaTab.jasper", parameters, Koneksi.koneksiDB());
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Tabungan/Laporan Semua Tabungan ("+s.format(ys)+").pdf")); // your output goes here
            exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}//GEN-LAST:event_LaporanPenabunganActionPerformed

private void LaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPeminjamanActionPerformed
        try {
            Date ys=new Date(); // membuat oject ys dari class Date 
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd"); //membuat object
            Map<String, Object> parameters = new HashMap<String, Object>();
            JasperPrint print = JasperFillManager.fillReport("./Laporan/semuaPinjaman.jasper", parameters, Koneksi.koneksiDB());
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Pinjaman/Laporan Semua Pinjaman ("+s.format(ys)+").pdf")); // your output goes here
            exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
 
}//GEN-LAST:event_LaporanPeminjamanActionPerformed

private void PrintLaporanTabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintLaporanTabunganActionPerformed
File namaFile = new File("./Laporan/semuaTab.jasper");
        try {           
            JasperReport jasper=(net.sf.jasperreports.engine.JasperReport)
            net.sf.jasperreports.engine.util.JRLoader.loadObject(namaFile.getPath());      
           JasperPrint jp=JasperFillManager.fillReport(jasper, null,Koneksi.koneksiDB());
            net.sf.jasperreports.view.JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
}//GEN-LAST:event_PrintLaporanTabunganActionPerformed

private void printLaporanPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLaporanPinjamActionPerformed
File namaFile = new File("./Laporan/semuaPinjaman.jasper");
        try {           
            JasperReport jasper=(net.sf.jasperreports.engine.JasperReport)
            net.sf.jasperreports.engine.util.JRLoader.loadObject(namaFile.getPath());      
           JasperPrint jp=JasperFillManager.fillReport(jasper, null,Koneksi.koneksiDB());
            net.sf.jasperreports.view.JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
}//GEN-LAST:event_printLaporanPinjamActionPerformed

private void prinLapByParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prinLapByParamActionPerformed
       try {
             
           String sql = "SELECT nama,jumlah,tanggal FROM `tabungan`,anggota where anggota.id = tabungan.ida and tanggal BETWEEN '"+t1.getText()+"'and"+"'"+t2.getText()+"'";
           Connection conn = (Connection) Koneksi.koneksiDB();
           Statement stm = (Statement) conn.createStatement();  
                    ResultSet rs = stm.executeQuery(sql);
                    JasperPrint jasperPrint;       
                    JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);            
                    JasperReport jasperReport = JasperCompileManager.compileReport("./Laporan/tabung.jrxml");          
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
                    JRViewer aViewer = new JRViewer(jasperPrint);                  
                    JDialog viewer = new JDialog(); 	
                    viewer.setTitle(".: Jasper Report :.");             
                    viewer.setAlwaysOnTop(true);
                    viewer.getContentPane().add(aViewer);                  
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();     
                    viewer.setBounds(0,0,screenSize.width, screenSize.height);
                    viewer.setVisible(true);              

                    stm.close();
               
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        }
}//GEN-LAST:event_prinLapByParamActionPerformed

private void lapTabByParammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapTabByParammActionPerformed
        try {
            String sql = "SELECT nama,jumlah,tanggal FROM `tabungan`,anggota where anggota.id = tabungan.ida and tanggal BETWEEN '"+t1.getText()+"'and"+"'"+t2.getText()+"'";
                  Connection conn = (Connection) Koneksi.koneksiDB();
                  Statement stm = (Statement) conn.createStatement();
                 ResultSet rs = stm.executeQuery(sql);
                 Map<String, Object> parameters = new HashMap<String, Object>(); 
                 JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);            
                 JasperReport jasperReport = JasperCompileManager.compileReport("./Laporan/tabung.jrxml");          
                 JasperPrint print = JasperFillManager.fillReport(jasperReport, null, jrRS); 
                 JRExporter exporter = new JRPdfExporter();
                 exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
                 exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Tabungan/Laporan Tabungan "+t1.getText()+" - "+t2.getText()+".pdf")); // your output goes here
                 exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}//GEN-LAST:event_lapTabByParammActionPerformed

private void LapPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapPinjamActionPerformed
        try {
            String sql = "SELECT nama,jumlahp,tanggalp FROM `pinjam`,anggota where anggota.id = pinjam.ida and tanggalp BETWEEN '"+t1.getText()+"'and"+"'"+t2.getText()+"'";
             Connection conn = (Connection) Koneksi.koneksiDB();
             Statement stm = (Statement) conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            Map<String, Object> parameters = new HashMap<String, Object>(); 
            JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);            
            JasperReport jasperReport = JasperCompileManager.compileReport("./Laporan/Peminjaman.jrxml");          
            JasperPrint print = JasperFillManager.fillReport(jasperReport, null, jrRS); 
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Pinjaman/Laporan Peminjaman "+t1.getText()+" - "+t2.getText()+".pdf")); // your output goes here
            exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}//GEN-LAST:event_LapPinjamActionPerformed

private void prinLapPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prinLapPinjamActionPerformed
 try {
           String sql = "SELECT nama,jumlahp,tanggalp FROM `pinjam`,anggota where anggota.id = pinjam.ida and tanggalp BETWEEN '"+t1.getText()+"'and"+"'"+t2.getText()+"'";
           Connection conn = (Connection) Koneksi.koneksiDB();
           Statement stm = (Statement) conn.createStatement();
          
         
                    ResultSet rs = stm.executeQuery(sql);
                    JasperPrint jasperPrint;       
                    JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);            
                    JasperReport jasperReport = JasperCompileManager.compileReport("./Laporan/Peminjaman.jrxml");          
                    jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
                    JRViewer aViewer = new JRViewer(jasperPrint);                  
                    JDialog viewer = new JDialog(); 	
                    viewer.setTitle(".: Jasper Report :.");             
                    viewer.setAlwaysOnTop(true);
                    viewer.getContentPane().add(aViewer);                  
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();     
                    viewer.setBounds(0,0,screenSize.width, screenSize.height);
                    viewer.setVisible(true);              

                    stm.close();
               
        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        }
}//GEN-LAST:event_prinLapPinjamActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Menu x = new Menu();
    x.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
        Desktop.getDesktop().open(new File("lap"));
    }
    catch(IOException ex)
    {
        JOptionPane.showMessageDialog(rootPane, "Not Found");
    }
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LapPinjam;
    private javax.swing.JButton LaporanPeminjaman;
    private javax.swing.JButton LaporanPenabungan;
    private javax.swing.JButton PrintLaporanTabungan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton lapTabByParamm;
    private javax.swing.JButton prinLapByParam;
    private javax.swing.JButton prinLapPinjam;
    private javax.swing.JButton printLaporanPinjam;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
