package teskop;


import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class Pengurus extends javax.swing.JFrame {

    /**
     * Creates new form Pengurus
     */
    public String nama,alamat,hp,jabatan,id,kataKunci;
    static int dasarCari;
    public Pengurus() {
        initComponents();
        getData();
        cari.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        namatext = new javax.swing.JTextField();
        alamattext = new javax.swing.JTextField();
        jabatantext = new javax.swing.JTextField();
        hptext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        del = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ad = new javax.swing.JButton();
        cr = new javax.swing.JComboBox();
        cari = new javax.swing.JButton();
        key = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bck = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cari1 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        namatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatextActionPerformed(evt);
            }
        });

        alamattext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamattextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel2.setText("Alamat");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel3.setText("Jabatan");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel4.setText("Telepon");

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/hps.png"))); // NOI18N
        del.setContentAreaFilled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/simpan.png"))); // NOI18N
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/tambah.png"))); // NOI18N
        ad.setContentAreaFilled(false);
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(142, 142, 142)
                                .addComponent(namatext, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(135, 135, 135)
                                .addComponent(alamattext, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(125, 125, 125)
                                .addComponent(jabatantext, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(123, 123, 123)
                                .addComponent(hptext, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(namatext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(alamattext, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatantext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hptext)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(del)
                    .addComponent(simpan)
                    .addComponent(ad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nama", "Alamat", "No Hp" }));
        cr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crMouseReleased(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/cari.png"))); // NOI18N
        cari.setContentAreaFilled(false);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        key.setText("Pencarian");

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/Main Menu.png"))); // NOI18N
        bck.setContentAreaFilled(false);
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/print.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/laporan daftar pengurus.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bck, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/text/MANAJEMEN-PENGURUS(1).png"))); // NOI18N

        cari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teskop/Button/clear.png"))); // NOI18N
        cari1.setContentAreaFilled(false);
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cr)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cari1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alamattextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamattextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamattextActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        getTabel();
        namatext.setText(nama);
        alamattext.setText(alamat);
        jabatantext.setText(jabatan);
        hptext.setText(hp);
    }//GEN-LAST:event_tabelMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Update u = new Update();
        String a1,a2,a3,a4;
        a1 = namatext.getText();
        a2 = alamattext.getText();
        a3 = jabatantext.getText();
        a4 = hptext.getText();
        System.out.println("bej"+a1+"::"+a2+"::"+a3+"::"+a4+"::"+id);
        u.upPengurus(a1, a2, a3, a4, id);
        Pengurus a = new Pengurus();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        // TODO add your handling code here:
        Menu m =  new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bckActionPerformed
    String n1, al1, j1, h1;
    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
            n1 = namatext.getText();
            al1 = alamattext.getText();
            j1 = jabatantext.getText();
            h1 = hptext.getText();
        if( "".equals(n1) || "".equals(al1) || "".equals(h1)|| "".equals(j1))
        {
            JOptionPane.showMessageDialog(null,"Belum keisi full");
            
        }
        else {
            
            Update u = new Update();
            u.tambahPengurus(n1, al1, j1, h1);
            Pengurus a = new Pengurus();
            a.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_adActionPerformed
    String x;
private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
     Update u = new Update();
     u.deletePengurus(id);
     Pengurus a = new Pengurus();
     a.setVisible(true);
     this.dispose();
}//GEN-LAST:event_delActionPerformed

private void namatextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_namatextActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date ys=new Date(); // membuat oject ys dari class Date 
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd"); //membuat object
           Map<String, Object> parameters = new HashMap<String, Object>();
           JasperPrint print = JasperFillManager.fillReport("./Laporan/Peng.jasper", parameters, Koneksi.koneksiDB());
           JRExporter exporter = new JRPdfExporter();
           exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
           exporter.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("./lap/Pengurus/Laporan Semua Pengurus("+s.format(ys)+").pdf")); // your output goes here
           exporter.exportReport();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Pengurus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Pengurus.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 File namaFile = new File("./Laporan/Peng.jasper");
        try {           
            JasperReport jasper=(net.sf.jasperreports.engine.JasperReport)
            net.sf.jasperreports.engine.util.JRLoader.loadObject(namaFile.getPath());      
           JasperPrint jp=JasperFillManager.fillReport(jasper, null,Koneksi.koneksiDB());
            net.sf.jasperreports.view.JasperViewer.viewReport(jp,false);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
}//GEN-LAST:event_jButton2ActionPerformed

private void crMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseReleased
    dasarCari = cr.getSelectedIndex();
    cari.setEnabled(true);System.out.print(dasarCari);
}//GEN-LAST:event_crMouseReleased

private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        try {
            kataKunci = key.getText();
            DefaultTableModel tabel1= new DefaultTableModel();
                tabel1.addColumn("Nama");
                tabel1.addColumn("Alamaat");
                tabel1.addColumn("Jabatan");
                tabel1.addColumn("hp");           
                   Connection conn = Koneksi.koneksiDB();
                   Statement stm = conn.createStatement();
                   ResultSet sql;
                   if(dasarCari==0){System.out.print("cari nama + "+kataKunci);
                    sql = stm.executeQuery("select * from pengurus where nama like '%"+kataKunci+"%';");}
                   else if(dasarCari==1){
                    sql = stm.executeQuery("select * from pengurus where alamat like '%"+kataKunci+"%';");}
                   else{
                    sql = stm.executeQuery("select * from pengurus where hp like '%"+kataKunci+"%';");    }
                   while(sql.next()){
                        tabel1.addRow(new Object[]{
                            sql.getString(2),
                            sql.getString(3),
                            sql.getString(4),
                            sql.getString(5)
                        });
                    }
                    tabel.setModel(tabel1);
        } catch (SQLException ex) {
            Logger.getLogger(Pengurus.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_cariActionPerformed

private void crMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crMouseClicked
    dasarCari = cr.getSelectedIndex();
    cari.setEnabled(true);
    System.out.print(dasarCari);
}//GEN-LAST:event_crMouseClicked

private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
// TODO add your handling code here:
    getData();
    
}//GEN-LAST:event_cari1ActionPerformed
    public void getData(){
        DefaultTableModel tabel1= new DefaultTableModel();
        tabel1.addColumn("Nama");
        tabel1.addColumn("Alamaat");
        tabel1.addColumn("Jabatan");
        tabel1.addColumn("hp");
        try {
           
           Connection conn = Koneksi.koneksiDB();
           Statement stm = conn.createStatement();
           ResultSet sql = stm.executeQuery("select * from pengurus");
           while(sql.next()){
                tabel1.addRow(new Object[]{
                    sql.getString(2),
                    sql.getString(3),
                    sql.getString(4),
                    sql.getString(5)
                });
            }
            tabel.setModel(tabel1);
        }catch (SQLException e) {
        }
    }
   
     public void getTabel(){
        try {
            int row=tabel.getSelectedRow();
            String tabel_kiri=(tabel.getModel().getValueAt(row, 0).toString());
            String hpp=(tabel.getModel().getValueAt(row, 3).toString());
            java.sql.Connection conn= (java.sql.Connection)Koneksi.koneksiDB();
            java.sql.Statement stm= conn.createStatement();
            java.sql.ResultSet sql= stm.executeQuery("select * from pengurus where nama='"+tabel_kiri+"' and hp = '"+hpp+"'" );
            if (sql.next()){
                id = sql.getString("idp");
                nama=sql.getString("nama");
                alamat=sql.getString("alamat");
                hp=sql.getString("hp");
                jabatan=sql.getString("jabatan");
            }
            
        }catch(Exception e){
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengurus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JTextField alamattext;
    private javax.swing.JButton bck;
    private javax.swing.JButton cari;
    private javax.swing.JButton cari1;
    private javax.swing.JComboBox cr;
    private javax.swing.JButton del;
    private javax.swing.JTextField hptext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jabatantext;
    private javax.swing.JTextField key;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField namatext;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
